name: Terraform CD - Deploy Infraestrutura (s3 existente)

# Workflow para deploy de infraestrutura com Terraform, config do disparo manual
on: 
  workflow_dispatch:
    inputs:
      s3_bucket_name:
        description: 'Terraform s3 Bucket Name'
        required: true
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: true
      aws_account_id:
        description: 'AWS Account ID'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:

    - name: Checkout Código
      uses: actions/checkout@v3

    - name: Mascarar Credenciais
      run: |
        echo "::add-mask::${{ github.event.inputs.aws_access_key_id }}"
        echo "::add-mask::${{ github.event.inputs.aws_secret_access_key }}"
        echo "::add-mask::${{ github.event.inputs.aws_session_token }}"
        echo "::add-mask::${{ github.event.inputs.aws_account_id }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS CLI 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
        aws-session-token: ${{ github.event.inputs.aws_session_token }}
        aws-region: ${{ github.event.inputs.aws_region }}
        
    - name: Verificar Credenciais AWS
      run: aws sts get-caller-identity
      
    - name: Gerar arquivo backend.tfvars
      working-directory: src/terraform
      run: |
          cat <<EOF > backend.tfvars
          bucket = "${{ github.event.inputs.s3_bucket_name }}"
          key    = "easyorder-infra/terraform.tfstate"
          region = "${{ github.event.inputs.aws_region }}"
          EOF

    - name: Terraform Init
      working-directory: src/terraform
      run: terraform init -backend-config=backend.tfvars -reconfigure

    - name: Terraform Validate
      working-directory: src/terraform
      run: terraform validate

    - name: Terraform Plan
      env: 
        TF_VAR_accountIdVoclabs: ${{ github.event.inputs.aws_account_id }}
      working-directory: src/terraform
      run: terraform plan -out=plan.out

    - name: Terraform Apply
      env: 
        TF_VAR_accountIdVoclabs: ${{ github.event.inputs.aws_account_id }}
      working-directory: src/terraform
      run: terraform apply -auto-approve
      
    - name: Update kubeconfig 
      run: | 
        aws eks update-kubeconfig --name easyorder --region ${{ github.event.inputs.aws_region }}
    
    - name: Install Metrics Server CRDs
      working-directory: src/terraform
      run: |
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
